# Generated by Django 2.0.5 on 2019-06-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(help_text='Enter Course Name', max_length=50)),
                ('description', models.TextField(help_text='Enter Course description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=20)),
                ('second_name', models.CharField(help_text='Enter your first name', max_length=20)),
                ('date_of_birth', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(help_text='Enter your phone')),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('block_student', models.BooleanField()),
                ('attended_lectures', models.IntegerField()),
                ('role', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students_registered', models.IntegerField()),
                ('registered_Teacher', models.ManyToManyField(related_name='registerAteacher', to='students.Person')),
                ('registered_course', models.ManyToManyField(to='students.Course')),
                ('registered_student', models.ManyToManyField(related_name='registerAstudent', to='students.Person')),
            ],
        ),
    ]
