# Generated by Django 2.0.5 on 2019-07-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
        migrations.AddField(
            model_name='person',
            name='AreYouStudent',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='attended_lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='block_student',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='registeredcourses',
            name='number_of_students_registered',
            field=models.IntegerField(null=True),
        ),
    ]
